/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import locadoraveiculo.AlugarVeiculo;
import metodostelas.CarregarComboBox;
import metodostelas.CarregarTabela;
import metodostelas.GerenciarBotoes;
import metodostelas.GerenciarCampos;

/**
 *
 * @author alexandre
 */
public class AlugarMoto extends javax.swing.JFrame {

    //variavel para indicar editar ou novo quando for salvar
    String botao;
    
    //array de aluguel
    static ArrayList<AlugarVeiculo> listaAluguelMoto;
    
    /**
     * Creates new form AlugarVeiculo
     */
    public AlugarMoto() {
        initComponents();
        
        //Maximizar a tela
        this.setExtendedState(MAXIMIZED_BOTH);
        
        //criar lista
        listaAluguelMoto = new ArrayList();
        
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoAlugarMoto, btnSalvarAlugarMoto, btnEditarAlugarMoto, 
                btnCancelarAlugarMoto, btnExcluirAlugarMoto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDataRetiradaAlugarMoto = new javax.swing.JLabel();
        lblDataDevolucaoAlugarMoto = new javax.swing.JLabel();
        lblClienteAlugarMoto = new javax.swing.JLabel();
        lblMotoAlugarMoto = new javax.swing.JLabel();
        txtDataRetiradaAlugarMoto = new javax.swing.JTextField();
        txtDataDevolucaoAlugarMoto = new javax.swing.JTextField();
        cmbClienteAlugarMoto = new javax.swing.JComboBox<>();
        cmbMotoAlugarMoto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlugarMoto = new javax.swing.JTable();
        btnNovoAlugarMoto = new javax.swing.JButton();
        btnSalvarAlugarMoto = new javax.swing.JButton();
        btnEditarAlugarMoto = new javax.swing.JButton();
        btnCancelarAlugarMoto = new javax.swing.JButton();
        btnExcluirAlugarMoto = new javax.swing.JButton();
        btnVoltarFromAlugarMoto2Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alugar Veículo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alugar Moto"));

        lblDataRetiradaAlugarMoto.setText("Data de Retirada");

        lblDataDevolucaoAlugarMoto.setText("Data de Devolução");

        lblClienteAlugarMoto.setText("Cliente");

        lblMotoAlugarMoto.setText("Moto");

        cmbClienteAlugarMoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cliente" }));

        cmbMotoAlugarMoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma moto" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataRetiradaAlugarMoto)
                    .addComponent(lblDataDevolucaoAlugarMoto)
                    .addComponent(lblClienteAlugarMoto)
                    .addComponent(lblMotoAlugarMoto))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataRetiradaAlugarMoto)
                    .addComponent(txtDataDevolucaoAlugarMoto)
                    .addComponent(cmbClienteAlugarMoto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMotoAlugarMoto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataRetiradaAlugarMoto)
                    .addComponent(txtDataRetiradaAlugarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDevolucaoAlugarMoto)
                    .addComponent(txtDataDevolucaoAlugarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbClienteAlugarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteAlugarMoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMotoAlugarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMotoAlugarMoto)))
        );

        tblAlugarMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data de Retirada", "Data de Devolução", "Quantidade de dias", "Cliente", "Moto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlugarMoto.getTableHeader().setReorderingAllowed(false);
        tblAlugarMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlugarMotoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlugarMoto);

        btnNovoAlugarMoto.setText("Novo");
        btnNovoAlugarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlugarMotoActionPerformed(evt);
            }
        });

        btnSalvarAlugarMoto.setText("Salvar");
        btnSalvarAlugarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlugarMotoActionPerformed(evt);
            }
        });

        btnEditarAlugarMoto.setText("Editar");
        btnEditarAlugarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlugarMotoActionPerformed(evt);
            }
        });

        btnCancelarAlugarMoto.setText("Cancelar");
        btnCancelarAlugarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAlugarMotoActionPerformed(evt);
            }
        });

        btnExcluirAlugarMoto.setText("Excluir");
        btnExcluirAlugarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAlugarMotoActionPerformed(evt);
            }
        });

        btnVoltarFromAlugarMoto2Menu.setText("Voltar");
        btnVoltarFromAlugarMoto2Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarFromAlugarMoto2MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnNovoAlugarMoto)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarAlugarMoto)
                .addGap(18, 18, 18)
                .addComponent(btnEditarAlugarMoto)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarAlugarMoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirAlugarMoto))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(btnVoltarFromAlugarMoto2Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovoAlugarMoto)
                        .addComponent(btnSalvarAlugarMoto)
                        .addComponent(btnEditarAlugarMoto)
                        .addComponent(btnCancelarAlugarMoto))
                    .addComponent(btnExcluirAlugarMoto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarFromAlugarMoto2Menu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarFromAlugarMoto2MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarFromAlugarMoto2MenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarFromAlugarMoto2MenuActionPerformed

    private void btnNovoAlugarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlugarMotoActionPerformed
        
        botao = "novo";
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovoEditar(btnNovoAlugarMoto, btnSalvarAlugarMoto, btnEditarAlugarMoto, 
                btnCancelarAlugarMoto, btnExcluirAlugarMoto);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.opcaoNovoEditar(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //carregar combo box
        CarregarComboBox.carregarClientes(cmbClienteAlugarMoto, CadastroCliente.listaClientes);
        CarregarComboBox.carregarMotos(cmbMotoAlugarMoto, CadastroMoto.listaMotos);
        
        txtDataRetiradaAlugarMoto.requestFocus();
                
    }//GEN-LAST:event_btnNovoAlugarMotoActionPerformed

    private void btnSalvarAlugarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlugarMotoActionPerformed
        
        int index1 = cmbClienteAlugarMoto.getSelectedIndex();
        int index2 = cmbMotoAlugarMoto.getSelectedIndex();
        
        if(txtDataRetiradaAlugarMoto.getText().equals("") ||
            txtDataDevolucaoAlugarMoto.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
            txtDataRetiradaAlugarMoto.requestFocus();
            
        } else if (index1 == 0) {
            
            //verifica se algum item foi selecionado
            JOptionPane.showMessageDialog(null, "Um cliente deve ser selecionado", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else if (index2 == 0){
        
            //verifica se algum item foi selecionado
            JOptionPane.showMessageDialog(null, "Um veículo deve ser selecionado", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else {
            
            if (botao.equals("novo"))   {
                    
            //cadastrar aluguel de moto
            listaAluguelMoto.add(AlugarVeiculo.cadastrarAluguelMoto(txtDataRetiradaAlugarMoto.getText(), 
                    txtDataDevolucaoAlugarMoto.getText(), CadastroCliente.listaClientes.get(index1 - 1), 
                    CadastroMoto.listaMotos.get(index2 - 1)));
            
            JOptionPane.showMessageDialog(null, "Aluguel cadastrado com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
            
            } else if (botao.equals("editar"))  {
                int index = tblAlugarMoto.getSelectedRow();
                
                //editar cliente
                AlugarVeiculo.editarAluguelMoto(listaAluguelMoto.get(index), txtDataRetiradaAlugarMoto.getText(), 
                    txtDataDevolucaoAlugarMoto.getText(), CadastroCliente.listaClientes.get(index1 - 1), 
                    CadastroMoto.listaMotos.get(index2 - 1));
                
                JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
            }
            
            //carregar os dados na tabela de alugar moto
            CarregarTabela.tabelaAluguelMotoLista(tblAlugarMoto, listaAluguelMoto);
            
            //limpar os campos
            GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
            
            txtDataRetiradaAlugarMoto.requestFocus();
        }
        
    }//GEN-LAST:event_btnSalvarAlugarMotoActionPerformed

    private void btnCancelarAlugarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAlugarMotoActionPerformed
        
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoCancelar(btnNovoAlugarMoto, btnSalvarAlugarMoto, btnEditarAlugarMoto, 
                btnCancelarAlugarMoto, btnExcluirAlugarMoto);
        
    }//GEN-LAST:event_btnCancelarAlugarMotoActionPerformed

    private void btnEditarAlugarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlugarMotoActionPerformed
        
        botao = "editar";
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovoEditar(btnNovoAlugarMoto, btnSalvarAlugarMoto, btnEditarAlugarMoto, 
                btnCancelarAlugarMoto, btnExcluirAlugarMoto);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.opcaoNovoEditar(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //carregar combo box
        CarregarComboBox.carregarClientes(cmbClienteAlugarMoto, CadastroCliente.listaClientes);
        CarregarComboBox.carregarMotos(cmbMotoAlugarMoto, CadastroMoto.listaMotos);
        
        txtDataRetiradaAlugarMoto.requestFocus();
        
    }//GEN-LAST:event_btnEditarAlugarMotoActionPerformed

    private void tblAlugarMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlugarMotoMouseClicked
        
        int index = tblAlugarMoto.getSelectedRow();   
        
        if (index >= 0 && index < listaAluguelMoto.size()) {
            
            //pegar dados da lista de motos alugadas
            AlugarVeiculo motosAlugadas = listaAluguelMoto.get(index);
            txtDataRetiradaAlugarMoto.setText(String.valueOf(motosAlugadas.getDataRetirada()));
            txtDataDevolucaoAlugarMoto.setText(String.valueOf(motosAlugadas.getDataDevolucao()));
            cmbClienteAlugarMoto.removeAllItems();
            cmbClienteAlugarMoto.addItem(motosAlugadas.getCliente().getNomeCompleto());
            cmbMotoAlugarMoto.removeAllItems();
            cmbMotoAlugarMoto.addItem(motosAlugadas.getMoto().getPlaca());
            
        }
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.itemTabela(btnNovoAlugarMoto, btnSalvarAlugarMoto, btnEditarAlugarMoto, 
                btnCancelarAlugarMoto, btnExcluirAlugarMoto);
        
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
    }//GEN-LAST:event_tblAlugarMotoMouseClicked

    private void btnExcluirAlugarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlugarMotoActionPerformed
        
        int index = tblAlugarMoto.getSelectedRow(); 
        
        if (index >= 0 && index < listaAluguelMoto.size()){
            listaAluguelMoto.remove(index);
        }
        
        //carregar os dados na tabela de clientes
        CarregarTabela.tabelaAluguelMotoLista(tblAlugarMoto, listaAluguelMoto);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarMoto, txtDataDevolucaoAlugarMoto, 
                    cmbClienteAlugarMoto, cmbMotoAlugarMoto);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoAlugarMoto, btnSalvarAlugarMoto, btnEditarAlugarMoto, 
                btnCancelarAlugarMoto, btnExcluirAlugarMoto);
        
    }//GEN-LAST:event_btnExcluirAlugarMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugarMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAlugarMoto;
    private javax.swing.JButton btnEditarAlugarMoto;
    private javax.swing.JButton btnExcluirAlugarMoto;
    private javax.swing.JButton btnNovoAlugarMoto;
    private javax.swing.JButton btnSalvarAlugarMoto;
    private javax.swing.JButton btnVoltarFromAlugarMoto2Menu;
    private javax.swing.JComboBox<String> cmbClienteAlugarMoto;
    private javax.swing.JComboBox<String> cmbMotoAlugarMoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClienteAlugarMoto;
    private javax.swing.JLabel lblDataDevolucaoAlugarMoto;
    private javax.swing.JLabel lblDataRetiradaAlugarMoto;
    private javax.swing.JLabel lblMotoAlugarMoto;
    private javax.swing.JTable tblAlugarMoto;
    private javax.swing.JTextField txtDataDevolucaoAlugarMoto;
    private javax.swing.JTextField txtDataRetiradaAlugarMoto;
    // End of variables declaration//GEN-END:variables
}
