/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import locadoraveiculo.AlugarVeiculo;
import metodostelas.CarregarComboBox;
import metodostelas.CarregarTabela;
import metodostelas.GerenciarBotoes;
import metodostelas.GerenciarCampos;

/**
 *
 * @author alexandre
 */
public class AlugarCarro extends javax.swing.JFrame {

    //variavel para indicar editar ou novo quando for salvar
    String botao;
    
    //array de aluguel
    static ArrayList<AlugarVeiculo> listaAluguelCarro;
    
    /**
     * Creates new form AlugarCarro
     */
    public AlugarCarro() {
        initComponents();

        //Maximizar a tela
        this.setExtendedState(MAXIMIZED_BOTH);
        
        //criar lista
        listaAluguelCarro = new ArrayList();
        
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoAlugarCarro, btnSalvarAlugarCarro, btnEditarAlugarCarro, 
                btnCancelarAlugarCarro, btnExcluirAlugarCarro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDataRetiradaAlugarCarro = new javax.swing.JLabel();
        lblDataDevolucaoAlugarCarro = new javax.swing.JLabel();
        lblClienteAlugarCarro = new javax.swing.JLabel();
        lblCarroAlugarCarro = new javax.swing.JLabel();
        cmbCarroAlugarCarro = new javax.swing.JComboBox<>();
        cmbClienteAlugarCarro = new javax.swing.JComboBox<>();
        txtDataRetiradaAlugarCarro = new javax.swing.JTextField();
        txtDataDevolucaoAlugarCarro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlugarCarro = new javax.swing.JTable();
        btnNovoAlugarCarro = new javax.swing.JButton();
        btnSalvarAlugarCarro = new javax.swing.JButton();
        btnEditarAlugarCarro = new javax.swing.JButton();
        btnCancelarAlugarCarro = new javax.swing.JButton();
        btnExcluirAlugarCarro = new javax.swing.JButton();
        btnVoltarFromAlugarCarro2Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alugar Carro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alugar Carro"));

        lblDataRetiradaAlugarCarro.setText("Data de Retirada");

        lblDataDevolucaoAlugarCarro.setText("Data de Devolução");

        lblClienteAlugarCarro.setText("Cliente");

        lblCarroAlugarCarro.setText("Carro");

        cmbCarroAlugarCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um carro" }));

        cmbClienteAlugarCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cliente" }));

        txtDataRetiradaAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataRetiradaAlugarCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarroAlugarCarro)
                    .addComponent(lblClienteAlugarCarro)
                    .addComponent(lblDataRetiradaAlugarCarro)
                    .addComponent(lblDataDevolucaoAlugarCarro))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataDevolucaoAlugarCarro)
                    .addComponent(cmbClienteAlugarCarro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCarroAlugarCarro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDataRetiradaAlugarCarro))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataRetiradaAlugarCarro)
                    .addComponent(txtDataRetiradaAlugarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataDevolucaoAlugarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataDevolucaoAlugarCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteAlugarCarro)
                    .addComponent(cmbClienteAlugarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarroAlugarCarro)
                    .addComponent(cmbCarroAlugarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblAlugarCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data de Retirada", "Data de Devolução", "Quantidade de Dias", "Cliente", "Carro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlugarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlugarCarroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlugarCarro);

        btnNovoAlugarCarro.setText("Novo");
        btnNovoAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlugarCarroActionPerformed(evt);
            }
        });

        btnSalvarAlugarCarro.setText("Salvar");
        btnSalvarAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlugarCarroActionPerformed(evt);
            }
        });

        btnEditarAlugarCarro.setText("Editar");
        btnEditarAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlugarCarroActionPerformed(evt);
            }
        });

        btnCancelarAlugarCarro.setText("Cancelar");
        btnCancelarAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAlugarCarroActionPerformed(evt);
            }
        });

        btnExcluirAlugarCarro.setText("Excluir");
        btnExcluirAlugarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAlugarCarroActionPerformed(evt);
            }
        });

        btnVoltarFromAlugarCarro2Menu.setText("Voltar");
        btnVoltarFromAlugarCarro2Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarFromAlugarCarro2MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoAlugarCarro)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarAlugarCarro)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarAlugarCarro)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarAlugarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirAlugarCarro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltarFromAlugarCarro2Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoAlugarCarro)
                    .addComponent(btnSalvarAlugarCarro)
                    .addComponent(btnEditarAlugarCarro)
                    .addComponent(btnCancelarAlugarCarro)
                    .addComponent(btnExcluirAlugarCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarFromAlugarCarro2Menu)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarFromAlugarCarro2MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarFromAlugarCarro2MenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarFromAlugarCarro2MenuActionPerformed

    private void txtDataRetiradaAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataRetiradaAlugarCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataRetiradaAlugarCarroActionPerformed

    private void btnNovoAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlugarCarroActionPerformed
                
        botao = "novo";
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovoEditar(btnNovoAlugarCarro, btnSalvarAlugarCarro, btnEditarAlugarCarro, 
                btnCancelarAlugarCarro, btnExcluirAlugarCarro);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.opcaoNovoEditar(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //carregar combo box
        CarregarComboBox.carregarClientes(cmbClienteAlugarCarro, CadastroCliente.listaClientes);
        CarregarComboBox.carregarCarros(cmbCarroAlugarCarro, CadastroCarro.listaCarros);
        
        txtDataRetiradaAlugarCarro.requestFocus();
        
    }//GEN-LAST:event_btnNovoAlugarCarroActionPerformed

    private void btnSalvarAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlugarCarroActionPerformed

        int index1 = cmbClienteAlugarCarro.getSelectedIndex();
        int index2 = cmbCarroAlugarCarro.getSelectedIndex();
        
        if(txtDataRetiradaAlugarCarro.getText().equals("") ||
            txtDataDevolucaoAlugarCarro.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
            txtDataRetiradaAlugarCarro.requestFocus();
            
        } else if (index1 == 0) {
            
            //verifica se algum item foi selecionado
            JOptionPane.showMessageDialog(null, "Um cliente deve ser selecionado", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else if (index2 == 0){
        
            //verifica se algum item foi selecionado
            JOptionPane.showMessageDialog(null, "Um veículo deve ser selecionado", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else {
            
            if (botao.equals("novo"))   {
                    
            //cadastrar aluguel de moto
            listaAluguelCarro.add(AlugarVeiculo.cadastrarAluguelCarro(txtDataRetiradaAlugarCarro.getText(), 
                    txtDataDevolucaoAlugarCarro.getText(), CadastroCliente.listaClientes.get(index1 - 1), 
                    CadastroCarro.listaCarros.get(index2 - 1)));
            
            JOptionPane.showMessageDialog(null, "Aluguel cadastrado com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
            
            } else if (botao.equals("editar"))  {
                int index = tblAlugarCarro.getSelectedRow();
                
                //editar cliente
                AlugarVeiculo.editarAluguelCarro(listaAluguelCarro.get(index), txtDataRetiradaAlugarCarro.getText(), 
                    txtDataDevolucaoAlugarCarro.getText(), CadastroCliente.listaClientes.get(index1 - 1), 
                    CadastroCarro.listaCarros.get(index2 - 1));
                
                JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
            }
            
            //carregar os dados na tabela de alugar moto
            CarregarTabela.tabelaAluguelCarroLista(tblAlugarCarro, listaAluguelCarro);
            
            //limpar os campos
            GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
            
            txtDataRetiradaAlugarCarro.requestFocus();
        }
        
    }//GEN-LAST:event_btnSalvarAlugarCarroActionPerformed

    private void btnEditarAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlugarCarroActionPerformed

        botao = "editar";
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovoEditar(btnNovoAlugarCarro, btnSalvarAlugarCarro, btnEditarAlugarCarro, 
                btnCancelarAlugarCarro, btnExcluirAlugarCarro);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.opcaoNovoEditar(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //carregar combo box
        CarregarComboBox.carregarClientes(cmbClienteAlugarCarro, CadastroCliente.listaClientes);
        CarregarComboBox.carregarCarros(cmbCarroAlugarCarro, CadastroCarro.listaCarros);
        
        txtDataRetiradaAlugarCarro.requestFocus();
        
    }//GEN-LAST:event_btnEditarAlugarCarroActionPerformed

    private void btnCancelarAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAlugarCarroActionPerformed

        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoCancelar(btnNovoAlugarCarro, btnSalvarAlugarCarro, btnEditarAlugarCarro, 
                btnCancelarAlugarCarro, btnExcluirAlugarCarro);
        
    }//GEN-LAST:event_btnCancelarAlugarCarroActionPerformed

    private void btnExcluirAlugarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlugarCarroActionPerformed

        int index = tblAlugarCarro.getSelectedRow(); 
        
        if (index >= 0 && index < listaAluguelCarro.size()){
            listaAluguelCarro.remove(index);
        }
        
        //carregar os dados na tabela de clientes
        CarregarTabela.tabelaAluguelCarroLista(tblAlugarCarro, listaAluguelCarro);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoAlugarCarro, btnSalvarAlugarCarro, btnEditarAlugarCarro, 
                btnCancelarAlugarCarro, btnExcluirAlugarCarro);
        
    }//GEN-LAST:event_btnExcluirAlugarCarroActionPerformed

    private void tblAlugarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlugarCarroMouseClicked

        int index = tblAlugarCarro.getSelectedRow();   
        
        if (index >= 0 && index < listaAluguelCarro.size()) {
            
            //pegar dados da lista de motos alugadas
            AlugarVeiculo carrosAlugados = listaAluguelCarro.get(index);
            txtDataRetiradaAlugarCarro.setText(String.valueOf(carrosAlugados.getDataRetirada()));
            txtDataDevolucaoAlugarCarro.setText(String.valueOf(carrosAlugados.getDataDevolucao()));
            cmbClienteAlugarCarro.removeAllItems();
            cmbClienteAlugarCarro.addItem(carrosAlugados.getCliente().getNomeCompleto());
            cmbCarroAlugarCarro.removeAllItems();
            cmbCarroAlugarCarro.addItem(carrosAlugados.getMoto().getPlaca());
            
        }
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.itemTabela(btnNovoAlugarCarro, btnSalvarAlugarCarro, btnEditarAlugarCarro, 
                btnCancelarAlugarCarro, btnExcluirAlugarCarro);
        
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtDataRetiradaAlugarCarro, txtDataDevolucaoAlugarCarro, 
                    cmbClienteAlugarCarro, cmbCarroAlugarCarro);
        
    }//GEN-LAST:event_tblAlugarCarroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlugarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlugarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlugarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlugarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAlugarCarro;
    private javax.swing.JButton btnEditarAlugarCarro;
    private javax.swing.JButton btnExcluirAlugarCarro;
    private javax.swing.JButton btnNovoAlugarCarro;
    private javax.swing.JButton btnSalvarAlugarCarro;
    private javax.swing.JButton btnVoltarFromAlugarCarro2Menu;
    private javax.swing.JComboBox<String> cmbCarroAlugarCarro;
    private javax.swing.JComboBox<String> cmbClienteAlugarCarro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarroAlugarCarro;
    private javax.swing.JLabel lblClienteAlugarCarro;
    private javax.swing.JLabel lblDataDevolucaoAlugarCarro;
    private javax.swing.JLabel lblDataRetiradaAlugarCarro;
    private javax.swing.JTable tblAlugarCarro;
    private javax.swing.JTextField txtDataDevolucaoAlugarCarro;
    private javax.swing.JTextField txtDataRetiradaAlugarCarro;
    // End of variables declaration//GEN-END:variables
}
