/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import locadoraveiculo.Carro;
import metodostelas.CarregarTabela;
import metodostelas.GerenciarBotoes;
import metodostelas.GerenciarCampos;
import static telas.CadastroMoto.listaMotos;

/**
 *
 * @author alexandre
 */
public class CadastroCarro extends javax.swing.JFrame {

    //variavel para indicar editar ou novo quando for salvar
    String botao;
    
    //array de motos
    static ArrayList<Carro> listaCarros;
    
    /**
     * Creates new form CadastrarVeiculo
     */
    public CadastroCarro() {
        initComponents();
        
        //criar lista
        listaCarros = new ArrayList();

        //Maximizar a tela
        this.setExtendedState(MAXIMIZED_BOTH);

        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDisponibilidade = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblPlacaCarro = new javax.swing.JLabel();
        lblMarcaCarro = new javax.swing.JLabel();
        lblModeloCarro = new javax.swing.JLabel();
        lblCorCarro = new javax.swing.JLabel();
        lblValorDiariaCarro = new javax.swing.JLabel();
        lblQtdPortasCarro = new javax.swing.JLabel();
        lblCombustivelCarro = new javax.swing.JLabel();
        lblDisponibilidadeCarro = new javax.swing.JLabel();
        txtPlacaCarro = new javax.swing.JTextField();
        txtMarcaCarro = new javax.swing.JTextField();
        txtModeloCarro = new javax.swing.JTextField();
        txtCorCarro = new javax.swing.JTextField();
        txtValorDiariaCarro = new javax.swing.JTextField();
        txtQtdPortasCarro = new javax.swing.JTextField();
        txtCombustivelCarro = new javax.swing.JTextField();
        rdoBtnDisponivel = new javax.swing.JRadioButton();
        rdoBtnIndisponivel = new javax.swing.JRadioButton();
        btnOkCadastroCarro = new javax.swing.JButton();
        btnSalvarCarro = new javax.swing.JButton();
        btnNovoCarro = new javax.swing.JButton();
        btnEditarCarro = new javax.swing.JButton();
        btnExcluirCarro = new javax.swing.JButton();
        btnPesquisarCarro = new javax.swing.JButton();
        btnCancelarCarro = new javax.swing.JButton();
        btnVoltarFromCarro2Menu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarroLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Carro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Carro"));

        lblPlacaCarro.setText("Placa");

        lblMarcaCarro.setText("Marca");

        lblModeloCarro.setText("Modelo");

        lblCorCarro.setText("Cor");

        lblValorDiariaCarro.setText("Valor Diária");

        lblQtdPortasCarro.setText("Quantidade de Portas");

        lblCombustivelCarro.setText("Combustível");

        lblDisponibilidadeCarro.setText("Disponibilidade");

        btnGroupDisponibilidade.add(rdoBtnDisponivel);
        rdoBtnDisponivel.setSelected(true);
        rdoBtnDisponivel.setText("Disponível");

        btnGroupDisponibilidade.add(rdoBtnIndisponivel);
        rdoBtnIndisponivel.setText("Indisponível");

        btnOkCadastroCarro.setText("OK");
        btnOkCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkCadastroCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlacaCarro)
                    .addComponent(lblMarcaCarro)
                    .addComponent(lblModeloCarro)
                    .addComponent(lblCorCarro)
                    .addComponent(lblValorDiariaCarro)
                    .addComponent(lblCombustivelCarro)
                    .addComponent(lblDisponibilidadeCarro)
                    .addComponent(lblQtdPortasCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoBtnDisponivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdoBtnIndisponivel)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorDiariaCarro)
                            .addComponent(txtCorCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModeloCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarcaCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtdPortasCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCombustivelCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOkCadastroCarro)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacaCarro)
                    .addComponent(txtPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkCadastroCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaCarro)
                    .addComponent(txtMarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloCarro)
                    .addComponent(txtModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorCarro)
                    .addComponent(txtCorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorDiariaCarro)
                    .addComponent(txtValorDiariaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdPortasCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdPortasCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCombustivelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCombustivelCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponibilidadeCarro)
                    .addComponent(rdoBtnDisponivel)
                    .addComponent(rdoBtnIndisponivel))
                .addGap(59, 59, 59))
        );

        btnSalvarCarro.setText("Salvar");
        btnSalvarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCarroActionPerformed(evt);
            }
        });

        btnNovoCarro.setText("Novo");
        btnNovoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCarroActionPerformed(evt);
            }
        });

        btnEditarCarro.setText("Editar");
        btnEditarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCarroActionPerformed(evt);
            }
        });

        btnExcluirCarro.setText("Excluir");
        btnExcluirCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCarroActionPerformed(evt);
            }
        });

        btnPesquisarCarro.setText("Pesquisar");
        btnPesquisarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCarroActionPerformed(evt);
            }
        });

        btnCancelarCarro.setText("Cancelar");
        btnCancelarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCarroActionPerformed(evt);
            }
        });

        btnVoltarFromCarro2Menu.setText("Voltar");
        btnVoltarFromCarro2Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarFromCarro2MenuActionPerformed(evt);
            }
        });

        tblCarroLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cor", "Valor Diária", "Quantidade de Portas", "Combustível", "Disponibilidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCarroLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarroListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCarroLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCarro)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnPesquisarCarro)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarCarro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltarFromCarro2Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCarro)
                    .addComponent(btnNovoCarro)
                    .addComponent(btnEditarCarro)
                    .addComponent(btnExcluirCarro)
                    .addComponent(btnPesquisarCarro)
                    .addComponent(btnCancelarCarro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarFromCarro2Menu)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarFromCarro2MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarFromCarro2MenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarFromCarro2MenuActionPerformed

    private void btnCancelarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCarroActionPerformed
       
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.limparTodosCampos(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoCancelar(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
    }//GEN-LAST:event_btnCancelarCarroActionPerformed

    private void btnSalvarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCarroActionPerformed
        
        if(txtPlacaCarro.getText().equals("") || txtMarcaCarro.getText().equals("") || 
                txtModeloCarro.getText().equals("") || txtCorCarro.getText().equals("") || 
                txtValorDiariaCarro.getText().equals("") ||
                txtQtdPortasCarro.getText().equals("") || txtCombustivelCarro.getText().equals("") ||
                (rdoBtnDisponivel.isSelected() == false && rdoBtnIndisponivel.isSelected() == false))   {
                
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
            txtPlacaCarro.requestFocus();
            
        } else {
            
            if (botao.equals("novo"))   {
                    
            boolean estaDisponivel = true;
            if (rdoBtnDisponivel.isSelected())  {
                estaDisponivel = true;
            } else  if (rdoBtnIndisponivel.isSelected())    {
                estaDisponivel = false;
            } else {
                JOptionPane.showMessageDialog(null, "É preciso selecionar a disponibilidade", "Messagem", JOptionPane.PLAIN_MESSAGE);
            }
            
            //cadastrar carro
            listaCarros.add(Carro.cadastrarMoto(txtPlacaCarro.getText(),
                                    txtMarcaCarro.getText(), txtModeloCarro.getText(), txtCorCarro.getText(), 
                                    Double.parseDouble(txtValorDiariaCarro.getText()), estaDisponivel, 
                                    Byte.parseByte(txtQtdPortasCarro.getText()), txtCombustivelCarro.getText()));
            
            JOptionPane.showMessageDialog(null, "Carro cadastrado com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
            
            } else if (botao.equals("editar"))  {
                
                int index = tblCarroLista.getSelectedRow();
                
                boolean estaDisponivel = true;
                if (rdoBtnDisponivel.isSelected())  {
                    estaDisponivel = true;
                } else  if (rdoBtnIndisponivel.isSelected())    {
                    estaDisponivel = false;
                } else {
                    JOptionPane.showMessageDialog(null, "É preciso selecionar a disponibilidade", "Messagem", JOptionPane.PLAIN_MESSAGE);
                }
                
                //editar carro
                Carro.editarCarro(listaCarros.get(index), txtPlacaCarro.getText(),
                                    txtMarcaCarro.getText(), txtModeloCarro.getText(), txtCorCarro.getText(), 
                                    Double.parseDouble(txtValorDiariaCarro.getText()), estaDisponivel, 
                                    Byte.parseByte(txtQtdPortasCarro.getText()), txtCombustivelCarro.getText());
                
                JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            
            //carregar os dados na tabela de clientes
            CarregarTabela.tabelaCarroLista(tblCarroLista, listaCarros);
            
            //limpar os campos
            GerenciarCampos.limparTodosCampos(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
            
            txtPlacaCarro.requestFocus();
            
        }
    }//GEN-LAST:event_btnSalvarCarroActionPerformed

    private void btnNovoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCarroActionPerformed

        botao = "novo";
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.opcaoNovoEditar(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovoEditar(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        txtPlacaCarro.requestFocus();
        
    }//GEN-LAST:event_btnNovoCarroActionPerformed

    private void btnEditarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCarroActionPerformed
        
        botao = "editar";
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.opcaoNovoEditar(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovoEditar(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
        txtPlacaCarro.requestFocus();
        
    }//GEN-LAST:event_btnEditarCarroActionPerformed

    private void btnExcluirCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCarroActionPerformed

        int index = tblCarroLista.getSelectedRow(); 
        
        if (index >= 0 && index < listaCarros.size()){
            listaCarros.remove(index);
        }
        
        //carregar os dados na tabela de clientes
        CarregarTabela.tabelaCarroLista(tblCarroLista, listaCarros);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
    }//GEN-LAST:event_btnExcluirCarroActionPerformed

    private void btnPesquisarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCarroActionPerformed
       
        if (listaCarros.isEmpty())   {
            
            JOptionPane.showMessageDialog(null, "Nenhum carro cadastrado para pesquisa!", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else {
        
            //limpar os campos
            GerenciarCampos.limparTodosCampos(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
            //desabilitar e habilitar botoes
            GerenciarBotoes.botaoPesquisar(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
            //desabilitar ou habilitar campos de texto
            GerenciarCampos.opcaoPesquisar(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
            txtPlacaCarro.requestFocus();
        }
    }//GEN-LAST:event_btnPesquisarCarroActionPerformed

    private void btnOkCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkCadastroCarroActionPerformed
        
        if (txtPlacaCarro.getText().equals(""))   {
            
            JOptionPane.showMessageDialog(null, "Nenhuma placa informado para pesquisa!", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else {
            Carro carro;
            
            String placaPesquisa = txtPlacaCarro.getText();
            
            String placa = "";
            String marca = "";
            String modelo = "";
            String cor = "";
            String valorDiaria = "";
            String estaDisponivel = "";
            String qtdPortas = "";
            String combustivel = "";
            
            for (int i = 0; i < listaCarros.size(); i++)  {
                
                carro = listaCarros.get(i);
                
                if (placaPesquisa.equals(carro.getPlaca()))   {
                    
                    placa = String.valueOf(carro.getPlaca());
                    marca = String.valueOf(carro.getMarca());
                    modelo = String.valueOf(carro.getModelo());
                    cor = String.valueOf(carro.getCor());
                    valorDiaria = String.valueOf(carro.getValorDiaria());
                    estaDisponivel = String.valueOf(carro.getEstaDisponivel());
                    qtdPortas = String.valueOf(carro.getQtdPortas());
                    combustivel = String.valueOf(carro.getCombustivel());
                    
                }
            }
            
            if (placaPesquisa.equals(""))  {
                
                JOptionPane.showMessageDialog(null, "Não existe carro cadastrada para esta placa!", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
                //limpar os campos
                GerenciarCampos.limparTodosCampos(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
                
            } else  {
            
                txtPlacaCarro.setText(placa);
                txtMarcaCarro.setText(marca);
                txtModeloCarro.setText(modelo);
                txtCorCarro.setText(cor);
                txtValorDiariaCarro.setText(valorDiaria); 
                txtCombustivelCarro.setText(combustivel);
                txtQtdPortasCarro.setText(qtdPortas);
                
                if (estaDisponivel.equals("true")) {
                    rdoBtnDisponivel.isSelected();
                } else if (estaDisponivel.equals("false")) {
                    rdoBtnIndisponivel.isSelected();
                }

            }
            
            txtPlacaCarro.selectAll();
            txtPlacaCarro.requestFocus();
            
        }
        
    }//GEN-LAST:event_btnOkCadastroCarroActionPerformed

    private void tblCarroListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarroListaMouseClicked

        int index = tblCarroLista.getSelectedRow();   
        
        if (index >= 0 && index < listaCarros.size()) {
            Carro carro = listaCarros.get(index);
            
            txtPlacaCarro.setText(String.valueOf(carro.getPlaca()));
            txtMarcaCarro.setText(String.valueOf(carro.getMarca()));
            txtModeloCarro.setText(String.valueOf(carro.getModelo()));
            txtCorCarro.setText(String.valueOf(carro.getCor()));
            txtValorDiariaCarro.setText(String.valueOf(carro.getValorDiaria())); 
            txtCombustivelCarro.setText(String.valueOf(carro.getCombustivel()));
            txtQtdPortasCarro.setText(String.valueOf(carro.getQtdPortas()));
            
            boolean estaDisponivel = carro.getEstaDisponivel();
            
            if (estaDisponivel == true) {
                rdoBtnDisponivel.isSelected();
            } else if (estaDisponivel == false) {
                rdoBtnIndisponivel.isSelected();
            }
        }
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.itemTabela(btnNovoCarro, btnSalvarCarro, btnEditarCarro, 
                btnCancelarCarro, btnPesquisarCarro, btnExcluirCarro, btnOkCadastroCarro);
        
        //desabilitar campos de texto
        GerenciarCampos.camposDefault(txtPlacaCarro, txtMarcaCarro, 
                    txtModeloCarro, txtCorCarro, txtValorDiariaCarro, 
                    txtCombustivelCarro, txtQtdPortasCarro, rdoBtnDisponivel, rdoBtnIndisponivel);
        
    }//GEN-LAST:event_tblCarroListaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCarro;
    private javax.swing.JButton btnEditarCarro;
    private javax.swing.JButton btnExcluirCarro;
    private javax.swing.ButtonGroup btnGroupDisponibilidade;
    private javax.swing.JButton btnNovoCarro;
    private javax.swing.JButton btnOkCadastroCarro;
    private javax.swing.JButton btnPesquisarCarro;
    private javax.swing.JButton btnSalvarCarro;
    private javax.swing.JButton btnVoltarFromCarro2Menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCombustivelCarro;
    private javax.swing.JLabel lblCorCarro;
    private javax.swing.JLabel lblDisponibilidadeCarro;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblPlacaCarro;
    private javax.swing.JLabel lblQtdPortasCarro;
    private javax.swing.JLabel lblValorDiariaCarro;
    private javax.swing.JRadioButton rdoBtnDisponivel;
    private javax.swing.JRadioButton rdoBtnIndisponivel;
    private javax.swing.JTable tblCarroLista;
    private javax.swing.JTextField txtCombustivelCarro;
    private javax.swing.JTextField txtCorCarro;
    private javax.swing.JTextField txtMarcaCarro;
    private javax.swing.JTextField txtModeloCarro;
    private javax.swing.JTextField txtPlacaCarro;
    private javax.swing.JTextField txtQtdPortasCarro;
    private javax.swing.JTextField txtValorDiariaCarro;
    // End of variables declaration//GEN-END:variables
}
