/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import locadoraveiculo.AlugarVeiculo;
import locadoraveiculo.Pagamento;
import metodostelas.CarregarComboBox;
import metodostelas.CarregarTabela;
import metodostelas.GerenciarBotoes;
import metodostelas.GerenciarCampos;

/**
 *
 * @author alexandre
 */
public class CadastrarPagamento extends javax.swing.JFrame {

    //array de motos
    static ArrayList<Pagamento> listaPagamento;
    static ArrayList<AlugarVeiculo> listaVeiculo;
    
    /**
     * Creates new form Pagamento
     */
    public CadastrarPagamento() {
        initComponents();
        
        //Maximizar a tela
        this.setExtendedState(MAXIMIZED_BOTH);
        
        listaPagamento = new ArrayList();
        listaVeiculo = new ArrayList();
        
        if (AlugarCarro.listaAluguelCarro.isEmpty() == false) {
            listaVeiculo.addAll(AlugarCarro.listaAluguelCarro);
        }
        
        if (AlugarMoto.listaAluguelMoto.isEmpty() == false) {
            listaVeiculo.addAll(AlugarMoto.listaAluguelMoto);
        }
        
        //desabilitar campos
        GerenciarCampos.camposDefault(rdoBtnNaoSeguro, rdoBtnSimSeguro, 
                rdoBtnBoleto, rdoBtnCartao, cmbAluguelCadastrado);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoPagamento, btnSalvarPagamento,
                btnCancelarPagamento, btnExcluirPagamento);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblFormaPagamento = new javax.swing.JLabel();
        rdoBtnCartao = new javax.swing.JRadioButton();
        rdoBtnBoleto = new javax.swing.JRadioButton();
        lblAluguelCadastrado = new javax.swing.JLabel();
        cmbAluguelCadastrado = new javax.swing.JComboBox<>();
        lblSeguro = new javax.swing.JLabel();
        rdoBtnSimSeguro = new javax.swing.JRadioButton();
        rdoBtnNaoSeguro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaPagamento = new javax.swing.JTable();
        btnNovoPagamento = new javax.swing.JButton();
        btnCancelarPagamento = new javax.swing.JButton();
        btnExcluirPagamento = new javax.swing.JButton();
        btnVoltarFromPagamento2Menu = new javax.swing.JButton();
        btnSalvarPagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionar Forma de Pagamento"));

        lblFormaPagamento.setText("Forma de Pagamento");

        buttonGroup1.add(rdoBtnCartao);
        rdoBtnCartao.setSelected(true);
        rdoBtnCartao.setText("Cartão");

        buttonGroup1.add(rdoBtnBoleto);
        rdoBtnBoleto.setText("Boleto Bancário");
        rdoBtnBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnBoletoActionPerformed(evt);
            }
        });

        lblAluguelCadastrado.setText("Aluguel cadastrado");

        cmbAluguelCadastrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um aluguel cadastrado" }));

        lblSeguro.setText("Seguro");

        buttonGroup2.add(rdoBtnSimSeguro);
        rdoBtnSimSeguro.setSelected(true);
        rdoBtnSimSeguro.setText("Sim");

        buttonGroup2.add(rdoBtnNaoSeguro);
        rdoBtnNaoSeguro.setText("Não");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormaPagamento)
                    .addComponent(lblAluguelCadastrado)
                    .addComponent(lblSeguro))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoBtnSimSeguro)
                            .addComponent(rdoBtnCartao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoBtnBoleto)
                            .addComponent(rdoBtnNaoSeguro)))
                    .addComponent(cmbAluguelCadastrado, 0, 1, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagamento)
                    .addComponent(rdoBtnCartao)
                    .addComponent(rdoBtnBoleto))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoBtnSimSeguro)
                    .addComponent(rdoBtnNaoSeguro)
                    .addComponent(lblSeguro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAluguelCadastrado)
                    .addComponent(cmbAluguelCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblListaPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Forma de Pagamento", "Seguro", "Desconto", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaPagamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaPagamento);

        btnNovoPagamento.setText("Novo");
        btnNovoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPagamentoActionPerformed(evt);
            }
        });

        btnCancelarPagamento.setText("Cancelar");
        btnCancelarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPagamentoActionPerformed(evt);
            }
        });

        btnExcluirPagamento.setText("Excluir");
        btnExcluirPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPagamentoActionPerformed(evt);
            }
        });

        btnVoltarFromPagamento2Menu.setText("Voltar");
        btnVoltarFromPagamento2Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarFromPagamento2MenuActionPerformed(evt);
            }
        });

        btnSalvarPagamento.setText("Salvar");
        btnSalvarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltarFromPagamento2Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoPagamento)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarPagamento)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirPagamento)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPagamento)
                    .addComponent(btnCancelarPagamento)
                    .addComponent(btnExcluirPagamento)
                    .addComponent(btnSalvarPagamento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarFromPagamento2Menu))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoBtnBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoBtnBoletoActionPerformed

    private void btnVoltarFromPagamento2MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarFromPagamento2MenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarFromPagamento2MenuActionPerformed

    private void btnNovoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPagamentoActionPerformed
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoNovo(btnNovoPagamento, btnSalvarPagamento,btnCancelarPagamento, btnExcluirPagamento);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(rdoBtnNaoSeguro, rdoBtnSimSeguro, 
                rdoBtnBoleto, rdoBtnCartao, cmbAluguelCadastrado);
        
                
        //carregar combo box
        CarregarComboBox.carregarAluguel(cmbAluguelCadastrado, listaVeiculo);

        
    }//GEN-LAST:event_btnNovoPagamentoActionPerformed

    private void btnSalvarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPagamentoActionPerformed

        int index = cmbAluguelCadastrado.getSelectedIndex();
        
        if(index == 0) {
                
            //verifica se algum item foi selecionado
            JOptionPane.showMessageDialog(null, "Um aluguel deve ser selecionado!", "Messagem", JOptionPane.PLAIN_MESSAGE);
            
        } else {
            
            String formaPagamento = "";
            if (rdoBtnBoleto.isSelected())  {
                formaPagamento = "Boleto Bancário";
            } else  if (rdoBtnCartao.isSelected())    {
                formaPagamento = "Cartão";
            } else {
                JOptionPane.showMessageDialog(null, "É preciso selecionar a forma de pagamento!", "Messagem", JOptionPane.PLAIN_MESSAGE);
            }
            
            boolean seguro = true;
            if (rdoBtnSimSeguro.isSelected())  {
                seguro = true;
            } else  if (rdoBtnNaoSeguro.isSelected())    {
                seguro = false;
            } else {
                JOptionPane.showMessageDialog(null, "É preciso informar a opção de seguro!", "Messagem", JOptionPane.PLAIN_MESSAGE);
            }
            
            //cadastrar pagamento
            listaPagamento.add(Pagamento.cadastrarPagamento(formaPagamento, seguro, listaVeiculo.get(index-1)));
            
            JOptionPane.showMessageDialog(null, "Aluguel cadastrado com sucesso!", "Messagem", JOptionPane.INFORMATION_MESSAGE);
            
            //carregar os dados na tabela de alugar moto
            CarregarTabela.tabelaPagamentoLista(tblListaPagamento, listaPagamento);
            
        }

    }//GEN-LAST:event_btnSalvarPagamentoActionPerformed

    private void btnCancelarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPagamentoActionPerformed
        
        //desabilitar campos de texto
        GerenciarCampos.limparTodosCampos(rdoBtnNaoSeguro, rdoBtnSimSeguro, 
                rdoBtnBoleto, rdoBtnCartao, cmbAluguelCadastrado);
        
        //desabilitar ou habilitar campos de texto
        GerenciarCampos.limparTodosCampos(rdoBtnNaoSeguro, rdoBtnSimSeguro, 
                rdoBtnBoleto, rdoBtnCartao, cmbAluguelCadastrado);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.botaoCancelar(btnNovoPagamento, btnSalvarPagamento,btnCancelarPagamento, btnExcluirPagamento);
        
        //desabilitar campos
        GerenciarCampos.camposDefault(rdoBtnNaoSeguro, rdoBtnSimSeguro, 
                rdoBtnBoleto, rdoBtnCartao, cmbAluguelCadastrado);
        
    }//GEN-LAST:event_btnCancelarPagamentoActionPerformed

    private void btnExcluirPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPagamentoActionPerformed
        
        int index = tblListaPagamento.getSelectedRow(); 
        
        if (index >= 0 && index < listaPagamento.size()){
            listaPagamento.remove(index);
        }
        
        //carregar os dados na tabela de clientes
        CarregarTabela.tabelaPagamentoLista(tblListaPagamento, listaPagamento);
        
        //limpar os campos
        GerenciarCampos.limparTodosCampos(rdoBtnNaoSeguro, rdoBtnSimSeguro, 
                rdoBtnBoleto, rdoBtnCartao, cmbAluguelCadastrado);
        
        //desabilitar e habilitar botoes
        GerenciarBotoes.iniciarTela(btnNovoPagamento, btnSalvarPagamento,
                btnCancelarPagamento, btnExcluirPagamento);
        
    }//GEN-LAST:event_btnExcluirPagamentoActionPerformed

    private void tblListaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaPagamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListaPagamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPagamento;
    private javax.swing.JButton btnExcluirPagamento;
    private javax.swing.JButton btnNovoPagamento;
    private javax.swing.JButton btnSalvarPagamento;
    private javax.swing.JButton btnVoltarFromPagamento2Menu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbAluguelCadastrado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAluguelCadastrado;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JRadioButton rdoBtnBoleto;
    private javax.swing.JRadioButton rdoBtnCartao;
    private javax.swing.JRadioButton rdoBtnNaoSeguro;
    private javax.swing.JRadioButton rdoBtnSimSeguro;
    private javax.swing.JTable tblListaPagamento;
    // End of variables declaration//GEN-END:variables
}
