/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadoraveiculo.Motorista;

/**
 *
 * @author alexandre
 */
public class CadastroMotoristas extends javax.swing.JFrame {
    
    String botao;
    
    static ArrayList<Motorista> listaMotoristas;

    /**
     * Creates new form CadastroMotorista
     */
    public CadastroMotoristas() {
        initComponents();
        
        listaMotoristas = new ArrayList();
        
        setLocationRelativeTo(null);
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //habilitar ou desabilitar campos de texto
        txtNome.setEnabled(false);
        txtId.setEnabled(false);
        txtCnh.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxChamadaMotorista.setEnabled(false);
    }
    
    //Carregar a tabela com motoristas da lista
    public void carregarTabelaMotoristas()    {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"id", "Nome", "Telefone", "CNH"}, 0 );
        
        for (int i = 0; i<listaMotoristas.size(); i++)    {
            Object linha[] = new Object[]{listaMotoristas.get(i).getIdMotorista(),
                                            listaMotoristas.get(i).getNome(),
                                            listaMotoristas.get(i).getTelefone(),
                                            listaMotoristas.get(i).getCnh()
                                        };
            
            modelo.addRow(linha);
        }
        
        //tabela recebe modelo
        tblMotoristas.setModel(modelo);
        
        tblMotoristas.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblMotoristas.getColumnModel().getColumn(1).setPreferredWidth(5);
        tblMotoristas.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblMotoristas.getColumnModel().getColumn(3).setPreferredWidth(5);      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlMotorista = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCnh = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCnh = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblChamadaMotorista = new javax.swing.JLabel();
        cbxChamadaMotorista = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        pnlMotoristas = new javax.swing.JScrollPane();
        tblMotoristas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Motoristas");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/motorista-48.png")).getImage());

        pnlMotorista.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Motorista"));

        lblID.setText("ID:");

        lblNome.setText("Nome:");

        lblTelefone.setText("Telefone:");

        lblCnh.setText("CNH:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtCnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnhActionPerformed(evt);
            }
        });

        btnOK.setText("OK");

        lblChamadaMotorista.setText("Chamada:");

        cbxChamadaMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlMotoristaLayout = new javax.swing.GroupLayout(pnlMotorista);
        pnlMotorista.setLayout(pnlMotoristaLayout);
        pnlMotoristaLayout.setHorizontalGroup(
            pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMotoristaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCnh)
                    .addComponent(lblTelefone)
                    .addComponent(lblNome)
                    .addComponent(lblID)
                    .addComponent(lblChamadaMotorista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMotoristaLayout.createSequentialGroup()
                        .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefone)
                            .addComponent(txtCnh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnOK))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxChamadaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );
        pnlMotoristaLayout.setVerticalGroup(
            pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMotoristaLayout.createSequentialGroup()
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCnh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChamadaMotorista)
                    .addComponent(cbxChamadaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair-24.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tblMotoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Telefone", "CNH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMotoristas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMotoristasMouseClicked(evt);
            }
        });
        pnlMotoristas.setViewportView(tblMotoristas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMotoristas)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtCnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnhActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        botao = "novo";

        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        
        //habilitar ou desabilitar campos de texto
        txtNome.setEnabled(true);
        txtId.setEnabled(true);
        txtCnh.setEnabled(true);
        txtTelefone.setEnabled(true);
        
        //habilitar ou desabilitar combo box
        cbxChamadaMotorista.setEnabled(true);
        
        //foco no campo de texto ID
        txtId.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        
        //habilitar ou desabilitar campos de texto
        txtNome.setEnabled(false);
        txtId.setEnabled(true);
        txtCnh.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxChamadaMotorista.setEnabled(false);
        
        //foco no campo de texto ID
        txtId.requestFocus();
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if (txtCnh.getText().equals("") || txtId.getText().equals("") || txtNome.getText().equals("") || txtTelefone.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Messagem", JOptionPane.PLAIN_MESSAGE);
            txtId.requestFocus();
            
        }else   {
            int idMotorista = Integer.parseInt(txtId.getText());
            String nome = txtNome.getText();
            String telefone = txtTelefone.getText();
            String cnh = txtCnh.getText();

            if(botao.equals("novo"))    {
            
                Motorista motorista = new Motorista(idMotorista, nome, telefone, cnh);
            
                listaMotoristas.add(motorista);

                JOptionPane.showMessageDialog(null, "Motorista cadastrado com sucesso", "Messagem", JOptionPane.INFORMATION_MESSAGE);

            } else if (botao.equals("editar"))  {
                
                int index = tblMotoristas.getSelectedRow();
                
                listaMotoristas.get(index).setCnh(cnh);
                listaMotoristas.get(index).setIdMotorista(idMotorista);
                listaMotoristas.get(index).setNome(nome);
                listaMotoristas.get(index).setTelefone(telefone);
            }
            
            
            
            //Carregar dados do motorista na tabela
            carregarTabelaMotoristas(); 
            
            //limpar campos de texto
            txtNome.setText("");
            txtId.setText("");
            txtCnh.setText("");
            txtTelefone.setText("");

            //limpar combo box
            cbxChamadaMotorista.setSelectedIndex(0);

            //habilitar ou desabilitar botoes
            btnNovo.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnEditar.setEnabled(false);
            btnOK.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnCancelar.setEnabled(false);

            //habilitar ou desabilitar campos de texto
            txtNome.setEnabled(false);
            txtId.setEnabled(false);
            txtCnh.setEnabled(false);
            txtTelefone.setEnabled(false);

            //habilitar ou desabilitar combo box
            cbxChamadaMotorista.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //limpar campos de texto
        txtNome.setText("");
        txtId.setText("");
        txtCnh.setText("");
        txtTelefone.setText("");
        
        //limpar combo box
        cbxChamadaMotorista.setSelectedIndex(0);
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //habilitar ou desabilitar campos de texto
        txtNome.setEnabled(false);
        txtId.setEnabled(false);
        txtCnh.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxChamadaMotorista.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblMotoristasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMotoristasMouseClicked

        int i = tblMotoristas.getSelectedRow();
        
        if (i >= 0 && i < listaMotoristas.size()) {
            Motorista motorista = listaMotoristas.get(i);
            txtCnh.setText(String.valueOf(motorista.getCnh()));
            txtId.setText(String.valueOf(motorista.getIdMotorista()));
            txtNome.setText(String.valueOf(motorista.getNome()));
            txtTelefone.setText(String.valueOf(motorista.getTelefone()));

        }
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(false);

        //habilitar ou desabilitar campos de texto
        txtNome.setEnabled(false);
        txtId.setEnabled(false);
        txtCnh.setEnabled(false);
        txtTelefone.setEnabled(false);
    }//GEN-LAST:event_tblMotoristasMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        botao = "editar";

        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);

        //habilitar ou desabilitar campos de texto
        txtNome.setEnabled(true);
        txtId.setEnabled(true);
        txtCnh.setEnabled(true);
        txtTelefone.setEnabled(true);
        
        txtId.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMotoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMotoristas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxChamadaMotorista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblChamadaMotorista;
    private javax.swing.JLabel lblCnh;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlMotorista;
    private javax.swing.JScrollPane pnlMotoristas;
    private javax.swing.JTable tblMotoristas;
    private javax.swing.JTextField txtCnh;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
