/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadoraveiculo.Cliente;

/**
 *
 * @author alexandre
 */
public class CadastroClientes extends javax.swing.JFrame {
    
    String botao;

    static ArrayList<Cliente> listaClientes;
    
    /**
     * Creates new form CadastroCliente
     */
    public CadastroClientes() {
        initComponents();
        
        listaClientes = new ArrayList();
        
        setLocationRelativeTo(null);
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //habilitar ou desabilitar campos de texto
        txtCPF.setEnabled(false);
        txtID.setEnabled(false);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxChamadaCliente.setEnabled(false);

    }
    
    //Carregar a tabela com clientes da lista
    public void carregarTabelaClientes()    {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID", "Nome", "Telefone", "CPF", "RG"}, 0 );
        
        for (int i = 0; i<listaClientes.size(); i++)    {
            Object linha[] = new Object[]{listaClientes.get(i).getIdCliente(),
                                            listaClientes.get(i).getNome(),
                                            listaClientes.get(i).getTelefone(),
                                            listaClientes.get(i).getCpf(),
                                            listaClientes.get(i).getRg()
                                        };
            
            modelo.addRow(linha);
        }
        
        //tabela recebe modelo
        tblClientes.setModel(modelo);
        
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(5);
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(5);      
        tblClientes.getColumnModel().getColumn(4).setPreferredWidth(5);      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVeiculo = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblChamadaCliente = new javax.swing.JLabel();
        cbxChamadaCliente = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario-64.png")).getImage());

        pnlVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        lblID.setText("ID:");

        lblRG.setText("RG:");

        lblCPF.setText("CPF:");

        lblNome.setText("Nome:");

        lblTelefone.setText("Telefone:");

        txtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGActionPerformed(evt);
            }
        });

        btnOK.setText("OK");

        lblChamadaCliente.setText("Chamada:");

        cbxChamadaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlVeiculoLayout = new javax.swing.GroupLayout(pnlVeiculo);
        pnlVeiculo.setLayout(pnlVeiculoLayout);
        pnlVeiculoLayout.setHorizontalGroup(
            pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVeiculoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblCPF)
                    .addComponent(lblID)
                    .addComponent(lblChamadaCliente))
                .addGap(84, 84, 84)
                .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVeiculoLayout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOK))
                    .addGroup(pnlVeiculoLayout.createSequentialGroup()
                        .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVeiculoLayout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTelefone))
                            .addGroup(pnlVeiculoLayout.createSequentialGroup()
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRG)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbxChamadaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVeiculoLayout.setVerticalGroup(
            pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChamadaCliente)
                    .addComponent(cbxChamadaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair-24.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "CPF", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        pnlClientes.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btnSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlClientes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        botao = "novo";

        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        
        //habilitar ou desabilitar campos de texto
        txtCPF.setEnabled(true);
        txtID.setEnabled(true);
        txtNome.setEnabled(true);
        txtRG.setEnabled(true);
        txtTelefone.setEnabled(true);
        
        //habilitar ou desabilitar combo box
        cbxChamadaCliente.setEnabled(true);
        
        //foco no campo de texto ID
        txtID.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        
        //habilitar ou desabilitar campos de texto
        txtCPF.setEnabled(false);
        txtID.setEnabled(true);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxChamadaCliente.setEnabled(false);
        
        //foco no campo de texto ID
        txtID.requestFocus();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        //limpar campos de texto
        txtCPF.setText("");
        txtID.setText("");
        txtNome.setText("");
        txtRG.setText("");
        txtTelefone.setText("");
        
        //limpar combo box
        cbxChamadaCliente.setSelectedIndex(0);
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //habilitar ou desabilitar campos de texto
        txtCPF.setEnabled(false);
        txtID.setEnabled(false);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxChamadaCliente.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (txtCPF.getText().equals("") || txtID.getText().equals("") || txtNome.getText().equals("") || txtRG.getText().equals("") || txtTelefone.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Messagem", JOptionPane.PLAIN_MESSAGE);
            txtID.requestFocus();
            
        }else   {        
            int idCliente = Integer.parseInt(txtID.getText());
            String rg = txtRG.getText();
            String cpf = txtCPF.getText();
            String nome = txtNome.getText();
            String telefone = txtTelefone.getText();

            if(botao.equals("novo"))    {   

                Cliente cliente = new Cliente(idCliente, rg, cpf, nome, telefone);

                listaClientes.add(cliente);
            
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso", "Messagem", JOptionPane.INFORMATION_MESSAGE);

            } else if (botao.equals("editar"))  {
                 
                int index = tblClientes.getSelectedRow();
                
                listaClientes.get(index).setCpf(cpf);
                listaClientes.get(index).setIdCliente(idCliente);
                listaClientes.get(index).setNome(nome);
                listaClientes.get(index).setRg(rg);
                listaClientes.get(index).setTelefone(telefone);
                
            }
            
            //Carregar dados do motorista na tabela
            carregarTabelaClientes();
            
            //limpar campos de texto
            txtCPF.setText("");
            txtID.setText("");
            txtNome.setText("");
            txtRG.setText("");
            txtTelefone.setText("");

            //limpar combo box
            cbxChamadaCliente.setSelectedIndex(0);

            //habilitar ou desabilitar botoes
            btnNovo.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnEditar.setEnabled(false);
            btnOK.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnCancelar.setEnabled(false);

            //habilitar ou desabilitar campos de texto
            txtCPF.setEnabled(false);
            txtID.setEnabled(false);
            txtNome.setEnabled(false);
            txtRG.setEnabled(false);
            txtTelefone.setEnabled(false);

            //habilitar ou desabilitar combo box
            cbxChamadaCliente.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked

        int i = tblClientes.getSelectedRow();
        
        if (i >= 0 && i < listaClientes.size()) {
            Cliente cliente = listaClientes.get(i);
            txtCPF.setText(String.valueOf(cliente.getCpf()));
            txtID.setText(String.valueOf(cliente.getIdCliente()));
            txtNome.setText(String.valueOf(cliente.getNome()));
            txtRG.setText(String.valueOf(cliente.getRg()));
            txtTelefone.setText(String.valueOf(cliente.getTelefone()));

        }
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(false);

        //habilitar ou desabilitar campos de texto
        txtCPF.setEnabled(false);
        txtID.setEnabled(false);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        botao = "editar";

        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);

        //habilitar ou desabilitar campos de texto
        txtCPF.setEnabled(true);
        txtID.setEnabled(true);
        txtNome.setEnabled(true);
        txtRG.setEnabled(true);
        txtTelefone.setEnabled(true);
        
        txtID.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxChamadaCliente;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblChamadaCliente;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JScrollPane pnlClientes;
    private javax.swing.JPanel pnlVeiculo;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
