/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadoraveiculo.Chamado;
import locadoraveiculo.Cliente;

/**
 *
 * @author alexandre
 */
public class CadastroChamados extends javax.swing.JFrame {
    
    static ArrayList<Chamado> listaChamados;
    
    String botao;

    /**
     * Creates new form CadastrarChamada
     */
    public CadastroChamados() {
        initComponents();
        
        listaChamados = new ArrayList();
        
        setLocationRelativeTo(null);
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //habilitar ou desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtHorarioPartida.setEnabled(false);
        txtHorarioRetorno.setEnabled(false);
        txtID.setEnabled(false);
        txtKMFinal.setEnabled(false);
        txtKMInicial.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
        txtValorTotal.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxCliente.setEnabled(false);
        cbxMotorista.setEnabled(false);
        cbxVeiculo.setEnabled(false);

    }
    
    //Carregar a tabela com chamados da lista
    public void carregarTabelaChamados()    {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID", "Data", "Tipo", "Origem", "Destino", "Horario Partida", "Horario Retorno", "KM Inicial", "KM Final", "Valor Total"}, 0 );
        
        for (int i = 0; i<listaChamados.size(); i++)    {
            Object linha[] = new Object[]{listaChamados.get(i).getIdChamado(),
                                            listaChamados.get(i).getData(),
                                            listaChamados.get(i).getTipo(),
                                            listaChamados.get(i).getOrigem(),
                                            listaChamados.get(i).getDestino(),
                                            listaChamados.get(i).getHorarioPartida(),
                                            listaChamados.get(i).getHorarioRetorno(),
                                            listaChamados.get(i).getKmInicial(),
                                            listaChamados.get(i).getKmFinal(),
                                            listaChamados.get(i).getValorTotal()
                                        };
            
            modelo.addRow(linha);
        }
        
        //tabela recebe modelo
        tblChamadas.setModel(modelo);
        
        tblChamadas.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(1).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(3).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(4).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(5).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(6).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(7).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(8).setPreferredWidth(5);
        tblChamadas.getColumnModel().getColumn(9).setPreferredWidth(5);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChamada = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblOrigem = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblHorarioPartida = new javax.swing.JLabel();
        lblHorarioRetorno = new javax.swing.JLabel();
        lblKMInicial = new javax.swing.JLabel();
        lblKMFinal = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtOrigem = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtHorarioPartida = new javax.swing.JTextField();
        txtHorarioRetorno = new javax.swing.JTextField();
        txtKMInicial = new javax.swing.JTextField();
        txtKMFinal = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblMotorista = new javax.swing.JLabel();
        lblVeiculo = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        cbxMotorista = new javax.swing.JComboBox<>();
        cbxVeiculo = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlChamadas = new javax.swing.JScrollPane();
        tblChamadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlChamada.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Chamada"));

        lblID.setText("ID:");

        lblData.setText("Data:");

        lblTipo.setText("Tipo:");

        lblOrigem.setText("Origem:");

        lblDestino.setText("Destino:");

        lblHorarioPartida.setText("Horario de Partida:");

        lblHorarioRetorno.setText("Horario de Retorno:");

        lblKMInicial.setText("Kilometragem Inicial:");

        lblKMFinal.setText("Kilometragem Final:");

        lblValorTotal.setText("Valor Total da Chamada:");

        btnOK.setText("OK");

        lblCliente.setText("Cliente:");

        lblMotorista.setText("Motorista:");

        lblVeiculo.setText("Veículo:");

        cbxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteActionPerformed(evt);
            }
        });

        cbxMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlChamadaLayout = new javax.swing.GroupLayout(pnlChamada);
        pnlChamada.setLayout(pnlChamadaLayout);
        pnlChamadaLayout.setHorizontalGroup(
            pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamadaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChamadaLayout.createSequentialGroup()
                        .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChamadaLayout.createSequentialGroup()
                                .addComponent(lblHorarioPartida)
                                .addGap(171, 171, 171)
                                .addComponent(lblHorarioRetorno))
                            .addGroup(pnlChamadaLayout.createSequentialGroup()
                                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlChamadaLayout.createSequentialGroup()
                                            .addGap(172, 172, 172)
                                            .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtHorarioPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(txtKMInicial)))
                                        .addGroup(pnlChamadaLayout.createSequentialGroup()
                                            .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblData)
                                                .addComponent(lblTipo)
                                                .addComponent(lblID))
                                            .addGap(138, 138, 138)
                                            .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(txtData)
                                                .addComponent(txtTipo)))
                                        .addGroup(pnlChamadaLayout.createSequentialGroup()
                                            .addComponent(lblOrigem)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblKMInicial))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOK)
                                    .addComponent(lblDestino)
                                    .addComponent(lblKMFinal))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtHorarioRetorno)
                            .addComponent(txtKMFinal)))
                    .addGroup(pnlChamadaLayout.createSequentialGroup()
                        .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorTotal)
                            .addComponent(lblCliente)
                            .addComponent(lblMotorista)
                            .addComponent(lblVeiculo))
                        .addGap(18, 18, 18)
                        .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlChamadaLayout.setVerticalGroup(
            pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblID)
                        .addComponent(btnOK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigem)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorarioPartida)
                    .addComponent(txtHorarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorarioRetorno)
                    .addComponent(txtHorarioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKMInicial)
                    .addComponent(txtKMInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKMFinal)
                    .addComponent(txtKMFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotorista)
                    .addComponent(cbxMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVeiculo)
                    .addComponent(cbxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair-24.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblChamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Tipo", "Origem", "Destino", "Horario Partida", "Horario Retorno", "KM Inicial", "KM Final", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChamadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamadasMouseClicked(evt);
            }
        });
        pnlChamadas.setViewportView(tblChamadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlChamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChamadas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        botao = "novo";
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        
        //habilitar ou desabilitar campos de texto
        txtData.setEnabled(true);
        txtDestino.setEnabled(true);
        txtHorarioPartida.setEnabled(true);
        txtHorarioRetorno.setEnabled(true);
        txtID.setEnabled(true);
        txtKMFinal.setEnabled(true);
        txtKMInicial.setEnabled(true);
        txtOrigem.setEnabled(true);
        txtTipo.setEnabled(true);
        txtValorTotal.setEnabled(true);
        
        //habilitar ou desabilitar combo box
        cbxCliente.setEnabled(true);
        cbxMotorista.setEnabled(true);
        cbxVeiculo.setEnabled(true);
        
        //foco no campo de texto ID
        txtID.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        
        //habilitar ou desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtHorarioPartida.setEnabled(false);
        txtHorarioRetorno.setEnabled(false);
        txtID.setEnabled(true);
        txtKMFinal.setEnabled(false);
        txtKMInicial.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
        txtValorTotal.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxCliente.setEnabled(false);
        cbxMotorista.setEnabled(false);
        cbxVeiculo.setEnabled(false);
        
        //foco no campo de texto ID
        txtID.requestFocus();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
 
        //Limpar os textos
        txtData.setText("");
        txtDestino.setText("");
        txtHorarioPartida.setText("");
        txtHorarioRetorno.setText("");
        txtID.setText("");
        txtKMFinal.setText("");
        txtKMInicial.setText("");
        txtOrigem.setText("");
        txtTipo.setText("");
        txtValorTotal.setText("");
        
        //limpar os combo box
        cbxCliente.setSelectedIndex(0);
        cbxMotorista.setSelectedIndex(0);
        cbxVeiculo.setSelectedIndex(0);
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //habilitar ou desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtHorarioPartida.setEnabled(false);
        txtHorarioRetorno.setEnabled(false);
        txtID.setEnabled(false);
        txtKMFinal.setEnabled(false);
        txtKMInicial.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
        txtValorTotal.setEnabled(false);
        
        //habilitar ou desabilitar combo box
        cbxCliente.setEnabled(false);
        cbxMotorista.setEnabled(false);
        cbxVeiculo.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    
        if (txtData.getText().equals("") || txtDestino.getText().equals("") || txtHorarioPartida.getText().equals("") ||
                txtHorarioRetorno.getText().equals("") || txtID.getText().equals("") || txtKMFinal.getText().equals("") || 
                txtKMInicial.getText().equals("") || txtOrigem.getText().equals("") ||
                txtTipo.getText().equals("") || txtValorTotal.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Messagem", JOptionPane.PLAIN_MESSAGE);
            txtID.requestFocus();
                       
        }else   {
            int idChamado = Integer.parseInt(txtID.getText());
            String data = txtData.getText();
            String tipo = txtTipo.getText();
            String origem = txtOrigem.getText();
            String destino = txtDestino.getText();
            float horarioPartida = Float.parseFloat(txtHorarioPartida.getText());
            float horarioRetorno = Float.parseFloat(txtHorarioRetorno.getText());
            double kmInicial = Double.parseDouble(txtKMInicial.getText());
            double kmFinal = Double.parseDouble(txtKMFinal.getText());
            double valorTotal = Double.parseDouble(txtValorTotal.getText());

            if(botao.equals("novo"))    {
            
                Chamado chamado = new Chamado(idChamado, data, tipo, origem, destino, horarioPartida, horarioRetorno, kmInicial, kmFinal, valorTotal);

                listaChamados.add(chamado);

                JOptionPane.showMessageDialog(null, "Chamado cadastrado com sucesso", "Messagem", JOptionPane.INFORMATION_MESSAGE);
        
            } else if (botao.equals("editar"))  {
                
                int index = tblChamadas.getSelectedRow();
                
                listaChamados.get(index).setIdChamado(idChamado);
                listaChamados.get(index).setData(data);
                listaChamados.get(index).setTipo(tipo);
                listaChamados.get(index).setOrigem(origem);
                listaChamados.get(index).setDestino(destino);
                listaChamados.get(index).setHorarioPartida(horarioPartida);
                listaChamados.get(index).setHorarioRetorno(horarioRetorno);
                listaChamados.get(index).setKmInicial(kmInicial);
                listaChamados.get(index).setKmFinal(kmFinal);
                listaChamados.get(index).setValorTotal(valorTotal);

            }
            
                
            
            //Carregar dados da chamada na tabela
            carregarTabelaChamados();


            //Limpar os textos
            txtData.setText("");
            txtDestino.setText("");
            txtHorarioPartida.setText("");
            txtHorarioRetorno.setText("");
            txtID.setText("");
            txtKMFinal.setText("");
            txtKMInicial.setText("");
            txtOrigem.setText("");
            txtTipo.setText("");
            txtValorTotal.setText("");

            //limpar os combo box
            cbxCliente.setSelectedIndex(0);
            cbxMotorista.setSelectedIndex(0);
            cbxVeiculo.setSelectedIndex(0);

            //habilitar ou desabilitar botoes
            btnNovo.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnEditar.setEnabled(false);
            btnOK.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnCancelar.setEnabled(false);

            //habilitar ou desabilitar campos de texto
            txtData.setEnabled(false);
            txtDestino.setEnabled(false);
            txtHorarioPartida.setEnabled(false);
            txtHorarioRetorno.setEnabled(false);
            txtID.setEnabled(false);
            txtKMFinal.setEnabled(false);
            txtKMInicial.setEnabled(false);
            txtOrigem.setEnabled(false);
            txtTipo.setEnabled(false);
            txtValorTotal.setEnabled(false);

            //habilitar ou desabilitar combo box
            cbxCliente.setEnabled(false);
            cbxMotorista.setEnabled(false);
            cbxVeiculo.setEnabled(false);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblChamadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamadasMouseClicked
 
        int i = tblChamadas.getSelectedRow();
        
        if (i >= 0 && i < listaChamados.size()) {
            Chamado chamado = listaChamados.get(i);
            txtID.setText(String.valueOf(chamado.getIdChamado()));
            txtData.setText(String.valueOf(chamado.getData()));
            txtTipo.setText(String.valueOf(chamado.getTipo()));
            txtOrigem.setText(String.valueOf(chamado.getOrigem()));
            txtDestino.setText(String.valueOf(chamado.getDestino()));
            txtHorarioPartida.setText(String.valueOf(chamado.getHorarioPartida()));
            txtHorarioRetorno.setText(String.valueOf(chamado.getHorarioRetorno()));
            txtKMInicial.setText(String.valueOf(chamado.getKmInicial()));
            txtKMFinal.setText(String.valueOf(chamado.getKmFinal()));
            txtValorTotal.setText(String.valueOf(chamado.getValorTotal()));

        }
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(false);

        //habilitar ou desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtHorarioPartida.setEnabled(false);
        txtHorarioRetorno.setEnabled(false);
        txtID.setEnabled(false);
        txtKMFinal.setEnabled(false);
        txtKMInicial.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
        txtValorTotal.setEnabled(false);
        
        
    }//GEN-LAST:event_tblChamadasMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        botao = "editar";
        
        //habilitar ou desabilitar botoes
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);

        //habilitar ou desabilitar campos de texto
        txtData.setEnabled(true);
        txtDestino.setEnabled(true);
        txtHorarioPartida.setEnabled(true);
        txtHorarioRetorno.setEnabled(true);
        txtID.setEnabled(true);
        txtKMFinal.setEnabled(true);
        txtKMInicial.setEnabled(true);
        txtOrigem.setEnabled(true);
        txtTipo.setEnabled(true);
        txtValorTotal.setEnabled(true);
        
        txtID.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroChamados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxMotorista;
    private javax.swing.JComboBox<String> cbxVeiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblHorarioPartida;
    private javax.swing.JLabel lblHorarioRetorno;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblKMFinal;
    private javax.swing.JLabel lblKMInicial;
    private javax.swing.JLabel lblMotorista;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JPanel pnlChamada;
    private javax.swing.JScrollPane pnlChamadas;
    private javax.swing.JTable tblChamadas;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtHorarioPartida;
    private javax.swing.JTextField txtHorarioRetorno;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKMFinal;
    private javax.swing.JTextField txtKMInicial;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
